from django.conf.urls import patterns, include, url
from .views import *
urlpatterns = patterns('',
	url(r'^$', inicio),
    url(r'^loguin/$', loguin),

    url(r'^docentes/$', docentes),
    url(r'^privado/$', privado),
    url(r'^salir/$', salir),
    url(r'^editarperfil/$',editar_perfil),
    url(r'^nuevo/$',nuevoUser.as_view(), name='nuevoUser'),
    url(r'^DatosUsuario/$', DatosUsuario, name='listaUsuarios'),
    url(r'^verificacion/$',verificacion, name='verificacion'),
    url(r'^imprimirHistorial/(?P<id>\d+)/$', imprimirHistorial),
    url(r'^PlanBimestral/$', PlanBimestral),
    url(r'^verPlanBimestral/$', verPlanBimestral),
    url(r'^newAvanse/$', newAvanse),
    url(r'^verAvances/$', verAvances),
    url(r'^nuevoDirector/$',nuevoDirector.as_view(), name='nuevoDirector'),
    url(r'^verDitectores/$', verDitectores, name='verDitectores'),

    url(r'^nuevoAlumno/$',nuevoAlumno.as_view(), name='nuevoAlumno'),
    url(r'^verAlumno', verAlumno, name='verAlumno'),
    url(r'^info/(?P<id>\d+)/$',Informacion),
    url(r'^NewAntecedente/$', NewAntecedente),
    url(r'^VerAntecedente/$', VerAntecedente),
    url(r'^buscarAlumno/$', buscarAlumno),
    url(r'^escogido/(?P<id>\d+)/$', escogido),
    url(r'^misAntecedentes/(?P<id>\d+)/$', VerAntecedente),
    url(r'^verHistorial/(?P<id>\d+)/$', verHistorial),
    url(r'^Darbaja/(?P<id>\d+)/$', Darbaja),
    url(r'^DarAlta/(?P<id>\d+)/$', DarAlta),
    url(r'^AltaAlumno/(?P<id>\d+)/$', AltaAlumno),
    url(r'^AlumnoVerDaja/(?P<id>\d+)/$', Darbaja),
    url(r'^DelAlumno/(?P<id>\d+)/$', DelAlumno),
    url(r'^AlumnoVerAlta/(?P<id>\d+)/$', DarAlta),
    url(r'^EditAlumno/(?P<id>\d+)/$', EditAlumno),
    url(r'^BajaAntecedente/(?P<id>\d+)/$', BajaAntecedente),
    url(r'^DelAntecedentes/(?P<id>\d+)/$', DelAntecedentes),
    url(r'^AltaAntecedente/(?P<id>\d+)/$', AltaAntecedente),
    url(r'^bajaAntecendetes/(?P<id>\d+)/$', bajaAntecendetes),
    url(r'^editAnte/(?P<id>\d+)/$', editAnte),
    url(r'^DarbajaDocente/(?P<id>\d+)/$', DarbajaDocente),
    url(r'^Deletedocente/(?P<id>\d+)/$', Deletedocente),
    url(r'^DarAltaDocente/(?P<id>\d+)/$', DarAltaDocente),
    url(r'^Altadocentes/(?P<id>\d+)/$', Altadocentes),
    url(r'^Canbiodirector/(?P<id>\d+)/$', Canbiodirector),
    url(r'^buscar/$', buscar),
    url(r'^nuevoAlumnoA/$', nuevoAlumnoA),
    url(r'^verHistoriales/$', verHistoriales),
    url(r'^por_curso/$', por_curso),
)